### ISSUE TITLE
Error running serverless-webpack on Windows since recent Node JS security update

### ISSUE THREAD

**Issue by massimocode** [medikoo/cli-progress-footer#2]
Please see the following:
https://github.com/serverless/serverless/issues/12434

Also this Node JS issue discussing the security change:
https://github.com/nodejs/node/issues/52554

It seems like adding a flag { shell: true } will resolve this

Thanks

**Comment by massimocode** [comment]
I've raised this in serverless-webpack instead, as it seems they are the one who is trying to spawn a `.cmd` file. Feel free to close the issue if it's not the responsibility of this module.

**Comment by medikoo** [comment]
@massimocode `cli-progress-footer` just decorates `spawn` and returns the value as it is. 

In this case _native_ `spawn` crashes with `EINVAL` and `cli-progress-footer` behaves properly by exposing the crash without obstruction.

I believe the issue is in `serverrless-webpack` which probably tries to call `npm.cmd` (or other _cmd_ program on windows) while this is no longer allowed with latest version of Node.js

**Comment by medikoo** [comment]
@massimocode I'm closing it, as I believe there's nothing to be done on `cli-progress-footer` side. If you feel otherwise please provide more details
